name: CD

on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 'Deploy this'
        run: 'echo "this should run after build"'