name: CD

on:
  push:
    branches:
      - main

  pull_request:
    type: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: 'Deploy this'
        run: 'echo "this should run after build"'