name: CI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

  pull_request:
    type: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 'Deploy this'
        run: 'echo "this should run after build"'